name: Unzip File in Repo

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch (you can choose your branch)

jobs:
  unzip-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      - name: Unzip GSMArenaDataset.zip
        run: |
          mkdir -p ./GSMArenaDataset  # Create the folder for unzipped files
          unzip -o ./GSMArenaDataset.zip -d ./GSMArenaDataset  # Unzip the file into that folder
          
      - name: Commit the unzipped files
        run: |
          git config --global user.name "KolenMG"
          git config --global user.email "mateigabrieltarangoiu@gmail.com"
          git add ./GSMArenaDataset/*  # Add the unzipped files to git
          git commit -m "Unzip GSMArenaDataset.zip"
          git push  # Push the unzipped files back to the repository
