name: Unzip File in Repo

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch (you can choose your branch)

jobs:
  unzip-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      - name: Unzip GSMArenaDataset.zip
        run: |
          mkdir -p ./GSMArenaDataset  # Create the folder for unzipped files
          unzip -o ./GSMArenaDataset.zip -d ./GSMArenaDataset  # Unzip the file into that folder
          
      - name: Commit data to repo
        run: |
          git config --global user.name "KolenMG"
          git config --global user.email "mateigabrieltarangoiu@gmail.com"
          git add GSMArenaDataset/*
          git commit -m "Add new data"
          git push https://x-access-token:${{ secrets.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 }}@github.com/KolenMG/PythonUpdate.git
